API_KEY = 'AIzaSyDjfyIEQ8KsW1FW0syChxbcLcsoyHcTVbo'
MAP_ID = 'fcfc3492ac8c3acc'
SHEET_URL = 'https://docs.google.com/spreadsheets/d/1m7nHxRXLXr4VQR1k_0ecx3O38btS7q6iTRPVYmsZ2ak'
SHEET_NAME = 'direcciones'
PROJECT_ID = 'emc-testgeocoding'
DATASET = 'testgeocoding'
TABLE_NAME = 'direcciones'